jps: https://github.com/jelastic-jps/webmail-lite/blob/master/manifest.jps
component: webmail-lite
stack:
  - nodeType: nginxphp
    nodeGroup: cp
  - nodeType: apachephp
    nodeGroup: cp
  - nodeType: mysql
    nodeGroup: sqldb